// A typed model for a project's sources.
//
// The on-the-wire shapes (the URL fragment in fragment-state.ts and the worker
// postMessage in worker-protocol.ts) stay FLAT and unchanged — `{ path, url?,
// content? }`. These helpers convert between that flat shape and an explicit
// discriminated union, so callers can branch on a source's kind instead of
// re-deriving it from which optional fields happen to be present.
//
// This module is intentionally pure and dependency-free: it introduces the
// union and the conversions without migrating any consumer, so the serialized
// boundaries are untouched until a later, deliberate step adopts it.
//
// Conversion is round-trip faithful for every flat shape that actually occurs
// in serialized state and at the worker boundary (text, unloaded/loaded remote,
// archive, in-memory binary). Two type-representable-but-never-produced shapes
// are normalized rather than preserved: a source carrying BOTH a `url` and
// binary `content` keeps only the url (remote content is text), and a `url`
// source whose `path` ends with `/` is always an archive regardless of any
// content. Neither combination is generated by the codebase today.

/** A source whose content is editable text held in memory. */
export type TextSource = { kind: 'text'; path: string; content: string };

/**
 * A source whose content is binary bytes held in memory. Only occurs at the
 * worker boundary (`CompileRequest` allows `Uint8Array` content); never appears
 * in fragment/persisted state, which is JSON and therefore text-only.
 */
export type BinarySource = { kind: 'binary'; path: string; content: Uint8Array };

/** A source fetched lazily from `url`; `content` is populated once loaded. */
export type RemoteSource = { kind: 'remote'; path: string; url: string; content?: string };

/** A directory mounted from a ZIP archive at `url`; its `path` ends with `/`. */
export type ArchiveSource = { kind: 'archive'; path: string; url: string };

export type ProjectSource = TextSource | BinarySource | RemoteSource | ArchiveSource;

/** The flat, untagged shape used at the worker boundary (allows binary). */
export type WireSource = { path: string; url?: string; content?: string | Uint8Array };

/** The flat shape used in the URL fragment / persisted state (text only). */
export type FragmentSource = { path: string; url?: string; content?: string };

/** A project source that can be represented in JSON (everything but binary). */
export type SerializableSource = Exclude<ProjectSource, BinarySource>;

/**
 * Classify a flat wire source into the union.
 *
 * Mapping (first match wins):
 * - `url` present and `path` ends with `/`  → archive
 * - `url` present                           → remote (carries `content` if a string)
 * - `content` is `Uint8Array`               → binary
 * - otherwise                               → text (absent content normalizes to '')
 *
 * The only normalization is the last branch: a bare `{ path }` with neither
 * `url` nor `content` becomes a text source with `content: ''`. State sources
 * always carry content or a url, so this degenerate shape does not occur in
 * serialized state; the normalization only affects the round-trip of an
 * otherwise-meaningless input.
 */
export function fromWire(wire: WireSource): ProjectSource {
  const { path, url, content } = wire;
  if (url != null) {
    if (path.endsWith('/')) return { kind: 'archive', path, url };
    return typeof content === 'string'
      ? { kind: 'remote', path, url, content }
      : { kind: 'remote', path, url };
  }
  if (content instanceof Uint8Array) return { kind: 'binary', path, content };
  return { kind: 'text', path, content: typeof content === 'string' ? content : '' };
}

/**
 * Flatten a union source back into the flat wire shape. Inverse of fromWire for
 * every shape the codebase produces; see the module header for the two
 * normalized edge cases where the round trip is not strictly identity.
 */
export function toWire(source: ProjectSource): WireSource {
  switch (source.kind) {
    case 'text':
    case 'binary':
      return { path: source.path, content: source.content };
    case 'remote':
      return source.content != null
        ? { path: source.path, url: source.url, content: source.content }
        : { path: source.path, url: source.url };
    case 'archive':
      return { path: source.path, url: source.url };
  }
}

/** Classify a fragment/persisted source (text-only) into the union. */
export function fromFragment(source: FragmentSource): SerializableSource {
  // A FragmentSource never carries binary content, so fromWire cannot return a
  // BinarySource here.
  return fromWire(source) as SerializableSource;
}

/** Flatten a serializable union source into the fragment/persisted shape. */
export function toFragment(source: SerializableSource): FragmentSource {
  return toWire(source) as FragmentSource;
}
