// DO NOT EDIT — generated by webpack-libs-plugin.js from libs-config.json
// Re-run `npm run build:libs` to regenerate.

export type ZipArchive = {
  name: string;
  zipPath: string;
  mountPath: string;
  repoUrl?: string;
  description?: string;
  docs?: Record<string, string>;
  symlinks?: Record<string, string>;
  prefetch?: boolean;
};

export const zipArchives: ZipArchive[] = [
  {"name":"openscad","zipPath":"./libraries/openscad.zip","mountPath":"/libraries/openscad","repoUrl":"https://github.com/openscad/openscad","description":"OpenSCAD","docs":{"CheatSheet":"https://openscad.org/cheatsheet/index.html","Documentation":"https://openscad.org/documentation.html"},"prefetch":false},
  {"name":"BOSL2","zipPath":"./libraries/BOSL2.zip","mountPath":"/libraries/BOSL2","repoUrl":"https://github.com/BelfrySCAD/BOSL2","description":"The Belfry OpenScad Library, v2.0","docs":{"CheatSheet":"https://github.com/BelfrySCAD/BOSL2/wiki/CheatSheet","Wiki":"https://github.com/BelfrySCAD/BOSL2/wiki"},"prefetch":true},
  {"name":"BOSL","zipPath":"./libraries/BOSL.zip","mountPath":"/libraries/BOSL","repoUrl":"https://github.com/revarbat/BOSL","description":"The Belfry OpenScad Library","prefetch":true},
  {"name":"NopSCADlib","zipPath":"./libraries/NopSCADlib.zip","mountPath":"/libraries/NopSCADlib","repoUrl":"https://github.com/nophead/NopSCADlib","prefetch":true},
  {"name":"funcutils","zipPath":"./libraries/funcutils.zip","mountPath":"/libraries/funcutils","repoUrl":"https://github.com/thehans/funcutils","description":"OpenSCAD collection of functional programming utilities","prefetch":true},
  {"name":"FunctionalOpenSCAD","zipPath":"./libraries/FunctionalOpenSCAD.zip","mountPath":"/libraries/FunctionalOpenSCAD","repoUrl":"https://github.com/thehans/FunctionalOpenSCAD","description":"Implementing OpenSCAD in OpenSCAD","prefetch":true},
  {"name":"YAPP_Box","zipPath":"./libraries/YAPP_Box.zip","mountPath":"/libraries/YAPP_Box","repoUrl":"https://github.com/mrWheel/YAPP_Box","description":"Yet Another Parametric Projectbox Box","prefetch":true},
  {"name":"MCAD","zipPath":"./libraries/MCAD.zip","mountPath":"/libraries/MCAD","repoUrl":"https://github.com/openscad/MCAD","description":"OpenSCAD Parametric CAD Library","prefetch":true},
  {"name":"boltsparts","zipPath":"./libraries/boltsparts.zip","mountPath":"/libraries/boltsparts","repoUrl":"https://github.com/boltsparts/boltsparts","description":"OpenSCAD library for generating bolt/nut models","docs":{"Usage":"https://boltsparts.github.io/en/docs/0.3/document/openscad/usage.html"},"prefetch":false},
  {"name":"OpenSCAD-Snippet","zipPath":"./libraries/OpenSCAD-Snippet.zip","mountPath":"/libraries/OpenSCAD-Snippet","repoUrl":"https://github.com/AngeloNicoli/OpenSCAD-Snippet","description":"OpenSCAD Snippet Library","symlinks":{"Asset_SCAD":"Asset_SCAD","Import_Library.scad":"Import_Library.scad"},"prefetch":false},
  {"name":"Stemfie_OpenSCAD","zipPath":"./libraries/Stemfie_OpenSCAD.zip","mountPath":"/libraries/Stemfie_OpenSCAD","repoUrl":"https://github.com/Cantareus/Stemfie_OpenSCAD","description":"OpenSCAD Stemfie Library","prefetch":true},
  {"name":"pathbuilder","zipPath":"./libraries/pathbuilder.zip","mountPath":"/libraries/pathbuilder","repoUrl":"https://github.com/dinther/pathbuilder","prefetch":false},
  {"name":"openscad_attachable_text3d","zipPath":"./libraries/openscad_attachable_text3d.zip","mountPath":"/libraries/openscad_attachable_text3d","repoUrl":"https://github.com/jon-gilbert/openscad_attachable_text3d","prefetch":false},
  {"name":"brailleSCAD","zipPath":"./libraries/brailleSCAD.zip","mountPath":"/libraries/brailleSCAD","repoUrl":"https://github.com/BelfrySCAD/brailleSCAD","docs":{"Documentation":"https://github.com/BelfrySCAD/brailleSCAD/wiki/TOC"},"prefetch":false},
  {"name":"smooth-prim","zipPath":"./libraries/smooth-prim.zip","mountPath":"/libraries/smooth-prim","repoUrl":"https://github.com/rcolyer/smooth-prim","description":"OpenSCAD smooth primitives library","symlinks":{"smooth_prim.scad":"smooth_prim.scad"},"prefetch":true},
  {"name":"plot-function","zipPath":"./libraries/plot-function.zip","mountPath":"/libraries/plot-function","repoUrl":"https://github.com/rcolyer/plot-function","description":"OpenSCAD Function Plotting Library","symlinks":{"plot_function.scad":"plot_function.scad"},"prefetch":true},
  {"name":"closepoints","zipPath":"./libraries/closepoints.zip","mountPath":"/libraries/closepoints","repoUrl":"https://github.com/rcolyer/closepoints","description":"OpenSCAD ClosePoints Library","symlinks":{"closepoints.scad":"closepoints.scad"},"prefetch":true},
  {"name":"UB.scad","zipPath":"./libraries/UB.scad.zip","mountPath":"/libraries/UB.scad","repoUrl":"https://github.com/UBaer21/UB.scad","symlinks":{"ub.scad":"ub.scad"},"prefetch":true},
  {"name":"openscad-tray","zipPath":"./libraries/openscad-tray.zip","mountPath":"/libraries/openscad-tray","repoUrl":"https://github.com/sofian/openscad-tray","description":"OpenSCAD library to create rounded rectangular trays with optional subdividers","symlinks":{"tray.scad":"tray.scad"},"prefetch":true},
  {"name":"lasercut","zipPath":"./libraries/lasercut.zip","mountPath":"/libraries/lasercut","repoUrl":"https://github.com/bmsleight/lasercut","description":"Module for OpenSCAD, allowing 3D models to be created from 2D lasercut parts","symlinks":{"lasercut.scad":"lasercut.scad"},"prefetch":false},
];

export const deployedArchiveNames: string[] = zipArchives.map(a => a.name);
