name: Test Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node: [
          {"name": "supported", "version": "24"},
          {"name": "latest", "version": "latest"}
        ]
    name: Node ${{ matrix.node.name }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v6
      - name: Setup node ${{ matrix.node.name }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node.version }}
      - run: npm ci

      - name: Cache build libs
        id: cache-libs
        uses: actions/cache@v4
        with:
          path: |
            libs/
            src/wasm/
            public/libraries/
          key: v2-libs-${{ hashFiles('libs-config.json') }}

      - name: Build libs (if cache miss)
        if: steps.cache-libs.outputs.cache-hit != 'true'
        run: npm run build:libs

      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-node-${{ matrix.node.name }}
          path: dist
          retention-days: 30
      - run: NODE_ENV=development npm run test:e2e
      - run: NODE_ENV=production  npm run test:e2e
